/**
 * 
 * @author Kyle Evangelisto
 * Represents an Instructor.
 * An Instructor has a name.
 * The methods here have been generated by eclipse.
 *
 */
public class Instructor implements RoleDisplayable { //Implements our abstract RoleDisplay class
	private String name;

	public Instructor(String name) {
		super();
		this.name = name;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Override
	public String toString() {
		return "Instructor [name=" + name + "]";
	}
	
	/**
	 * An overridden method from the RoleDisplay interface to over write the 
	 * the Role with Instructor, as an instructor is not a student.
	 */
	@Override
	public void displayNameAndRole() {
		System.out.println(getName() + ", Instructor");
	}
	
	
}
