/**
 * 
 * @author Kyle Evangelisto
 * A method representing a student.
 * A student has a name.
 * The methods here have been generated by eclipse.
 *
 */
public class Student implements RoleDisplayable { //Implements our abstract RoleDisplay class
	
	private String name;

	public Student(String name) {
		super();
		this.name = name;
	}
	
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Override
	public String toString() {
		return "Student [name=" + name + "]";
	}
	

}
